### ISSUE TITLE
通过tg机器人发送的带图片的消息无法在网页中看到图片

### ISSUE THREAD

**Issue by zhishixiang** [usememos/memos#2375]
### Describe the bug

![image](https://github.com/usememos/memos/assets/59593524/4d57307c-ab53-4b4c-8ed7-121c842da7c8)
![image](https://github.com/usememos/memos/assets/59593524/d6cc5f92-f0ac-4bcb-b9ac-2f9c8770a886)
![image](https://github.com/usememos/memos/assets/59593524/76fb8343-06b7-4a81-91f2-b5f5dec70f4a)
如图所示，资源库中能找到该图片，但是显示未使用且网页对应的消息没有图片显示。一开始使用cloudflare r2作为存储库，后面切换为本地存储但是没有任何效果，仍然不显示图片。

### Steps to reproduce

通过tg机器人发送想法

**Comment by zhishixiang** [comment]
![photo_2023-10-10_22-30-22](https://github.com/usememos/memos/assets/59593524/62997d5d-8c51-4e43-876d-7a278dfef936)
![photo_2023-10-10_22-30-36](https://github.com/usememos/memos/assets/59593524/0a12aad9-0171-40dd-b69a-87d1885baa3b)

部分图片没传上来，在此进行补充

**Comment by malinkang** [comment]
I have the same problem

**Comment by athurg** [comment]
I can't reproduce this problem. It looks like something wrong about R2.

**Comment by athurg** [comment]
Update: this issue maybe not because of the storage (R2), it because of a style calculation errors on the image while it's still loading while the page rendered. I have pushed a PR to fix it.

**Comment by wangweitung** [comment]
error still occur on docker latest version
![image](https://github.com/usememos/memos/assets/8080125/1c1dd293-d253-47cd-8b80-2db71177f44d)

error log
```
{"time":"2023-12-20T02:34:56Z","latency":"1.9462ms","method":"GET","uri":"/api/v1/memo/stats?creatorUsername=test","status":200,"error":""},
{"time":"2023-12-20T02:34:55Z","latency":"9.235784ms","method":"GET","uri":"/api/v1/memo?creatorUsername=test&rowStatus=NORMAL&limit=20","status":200,"error":""},
{"time":"2023-12-20T02:34:55Z","latency":"1.885542ms","method":"POST","uri":"/memos.api.v2.TagService/ListTags","status":200,"error":""},
{"time":"2023-12-20T02:34:55Z","latency":"2.13953ms","method":"POST","uri":"/memos.api.v2.InboxService/ListInboxes","status":200,"error":""},
{"time":"2023-12-20T02:34:55Z","latency":"1.836132ms","method":"POST","uri":"/memos.api.v2.UserService/GetUser","status":200,"error":""},
{"time":"2023-12-20T02:34:55Z","latency":"3.165563ms","method":"POST","uri":"/memos.api.v2.TagService/ListTags","status":200,"error":""}

```

**Comment by athurg** [comment]
There's a new bug in the latest version, but it has no relations about this.

Please refer #2650 .
