### ISSUE TITLE
safari ！An error occurs when the iPhone is opened

### ISSUE THREAD

**Issue by paluo90** [usememos/memos#2639]
### Describe the bug

Describe the bug

If you use Safari to open the website, the following error occurs！

ios16.3.1 ，iphone14pro！

- —————— -
Unexpected Application Error!
Invalid regular expression: invalid group specifier name
RegExp@[native code]
module code@https://****.com/assets/MemoResourceListView-8931b1bc.js:270:88898
evaluate@[native code]
moduleEvaluation@[native code]
moduleEvaluation@[native code]
moduleEvaluation@[native code]
@[native code]
asyncFunctionResume@[native code]
@[native code]
promiseReactionJobWithoutPromise@[native code]
promiseReactionJob@[native code]

### Steps to reproduce

1，Log in to my website，Register an account
2，A bug occurs ，
3，Uninstall and reinstall，still exists

### Screenshots or additional context

![15EB3DA3-4931-49D9-B6AB-B1C68494B242](https://github.com/usememos/memos/assets/154269470/3b4c007e-e5d3-44c9-8d0f-3b99f979bf1b)

**Comment by paluo90** [comment]
Using docker to install and log in is normal, but the iPhone prompts a bug.
Yes, I use my iPhone to log into my website and write，but encountered a problem

**Comment by jhademcconnell** [comment]
@paluo90 what version of Memos are you running? This may be similar to this issue: https://github.com/usememos/memos/issues/2633

Try updating to the latest version or re-building/re-deploying your Memo instance

**Comment by paluo90** [comment]
> @paluo90 what version of Memos are you running? This may be similar to this issue: #2633
> 
> Try updating to the latest version or re-building/re-deploying your Memo instance

It doesn't look like it，version V0.18, but it still doesn’t work，I reinstalled version V0.18, but it still doesn’t work.

**Comment by jhademcconnell** [comment]
@paluo90 I’m not able to recreate this error in my Memo instance v0.18.1 using iOS 17 and safari.

Have you tried accessing your website on a different device like desktop or Android to see if it works?

**Comment by paluo90** [comment]
> @paluo90 I’m not able to recreate this error in my Memo instance v0.18.1 using iOS 17 and safari.
> 
> Have you tried accessing your website on a different device like desktop or Android to see if it works?
I am ios16, on ipados16 can be opened normally, android can be opened normally, what is the reason for this?

**Comment by paluo90** [comment]
> @paluo90 I’m not able to recreate this error in my Memo instance v0.18.1 using iOS 17 and safari.
> 
> Have you tried accessing your website on a different device like desktop or Android to see if it works?

I am ios16, on ipados16 can be opened normally, android can be opened normally, what is the reason for this?

**Comment by qxxiao** [comment]
@paluo90 maybe related to ios version, the latest 17 is ok

**Comment by paluo90** [comment]
@qxxiao My God, if update the latest ios, I don't want to do that, maybe it is not possible to solve it fundamentally

**Comment by paluo90** [comment]
By the way, I forgot one thing, I had no problem logging in to the demo station with my iPhone, and when I installed it, there was a problem with my web page, so... This may be an issue to be fixed

**Comment by paluo90** [comment]
@okhanyu hello！

**Comment by tenebrisnox** [comment]
Just to add I'm having the same issue with my iphone with both Safari and Firefox.
I'm on iOS 15.8 - on an iphone 7. All was fine until the 18.0 update. The MoeMemos app still works ok.

**Comment by nibazshab** [comment]
The same problem, and my iphone is on iOS 15.4.1

**Comment by boojack** [comment]
Maybe fixed in the latest version. Please give a try in demo site: https://demo.usememos.com

**Comment by paluo90** [comment]
@boojack Sorry, the official demo site doesn't have this problem, but my own site still exists, version v0.18.1

**Comment by tenebrisnox** [comment]
@boojack The demo site works fine. I have a 0.18.1 docker installation. It was working up until 0.18.0.

**Comment by boojack** [comment]
Let's wait for the next release.

**Comment by chxsamidare** [comment]
the same problem on ipad safari and chrome

**Comment by aefa6** [comment]
ios14 is also not worked

**Comment by Stars521** [comment]
ios11 is also not worked

**Comment by jhademcconnell** [comment]
@Stars521 @aefa6 @chxsamidare on your iOS devices, can you go into your web browser settings (Safari if that's your default browser), clear all of Safari's cache/history, and then re-try to see if this issue still happens on those devices?

**Comment by aefa6** [comment]
Sorry, I am unable to assist you with testing as I have already reverted the version of "memos" to 0.17

**Comment by Stars521** [comment]
> @Stars521 @aefa6 @chxsamidare on your iOS devices, can you go into your web browser settings (Safari if that's your default browser), clear all of Safari's cache/history, and then re-try to see if this issue still happens on those devices?

This is the iPhone 11 accessing the website in incognito mode. It is still the same problem as before. The same error message is reported.
![WechatIMG38](https://github.com/usememos/memos/assets/57618656/d2940769-4a6d-4924-93e4-7c0fbbe2a75e)

**Comment by Stars521** [comment]
> @Stars521 @aefa6 @chxsamidare on your iOS devices, can you go into your web browser settings (Safari if that's your default browser), clear all of Safari's cache/history, and then re-try to see if this issue still happens on those devices?

This is the iPhone 11 accessing the website in incognito mode. It is still the same problem as before. The same error message is reported.
![WechatIMG39](https://github.com/usememos/memos/assets/57618656/2c50a49d-37be-4b46-bff4-fc722c01876f)

**Comment by jhademcconnell** [comment]
@Stars521 and that error message still happens after you cleared the web browser you are using’s cache in settings?

**Comment by xxzj990** [comment]
> > @Stars521 @aefa6 @chxsamidare on your iOS devices, can you go into your web browser settings (Safari if that's your default browser), clear all of Safari's cache/history, and then re-try to see if this issue still happens on those devices?
> 
> This is the iPhone 11 accessing the website in incognito mode. It is still the same problem as before. The same error message is reported. ![WechatIMG39](https://private-user-images.githubusercontent.com/57618656/294722517-2c50a49d-37be-4b46-bff4-fc722c01876f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNjQ4NDgsIm5iZiI6MTcwNTM2NDU0OCwicGF0aCI6Ii81NzYxODY1Ni8yOTQ3MjI1MTctMmM1MGE0OWQtMzdiZS00YjQ2LWJmZjQtZmM3MjJjMDE4NzZmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDAwMjIyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyYWM4YTA5ODY4NTg4Nzc2MDFiN2ZjMGQwZDQ3NjUzN2FhMmM4ZjIzOGYxNzM0NGM0MWNjMDY4OWM3MTBjNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3LUvVqlBWeeZymJlHK5hIBwR34pC_IkE_THH4j_5EwY)

0.18.2 works fine
ios15.4.1

**Comment by sulisu** [comment]
0.26.1 does not work on iphone 7 plus 15.8.4, safari and chrome show similar error code 

<img width="310" height="552" alt="Image" src="https://github.com/user-attachments/assets/531cb091-8971-47ff-ae3a-e2c49068b59d" />
