### ISSUE TITLE
Wrong tag count

### ISSUE THREAD

**Issue by Shen-Chris** [usememos/memos#4275]
### Describe the bug

Wrong tag count
标签计数错误

### Steps to reproduce

New tag: #DSQ has two notes, #DSQ/2024 has three notes, #DSQ/2025 has one note, but #DSQ is displayed as (2) in the tag tree filter on the right, but you can actually see 2+3+1=6 notes when you click

新增标签
#DSQ 下有两篇笔记，  #DSQ/2024 下有三篇笔记， #DSQ/2025下有一篇笔记，但是右侧标签树形筛选里#DSQ显示的是（2），但是点击实际能看到2+3+1=6篇

### The version of Memos you're using

Version: v0.23.0

**Comment by boojack** [comment]
Fixed with https://github.com/usememos/memos/commit/012ca1d780908351c3b71797287940189b295f27

**Comment by jeroendee** [comment]
@boojack this wrong account is still occurring on v0.25.0

<img width="759" alt="Image" src="https://github.com/user-attachments/assets/9df1be6a-d273-466b-9e08-37bdf9a871ae" />
