### ISSUE TITLE
Comments amount different on memos list and memos details

### ISSUE THREAD

**Issue by szonov** [usememos/memos#4608]
### Describe the bug

On memos list shown total comments amount, on memos detail page shown only own comments amount and own comments.
using api : /api/v1/{name}/comments returns all comments as expected own and someone else's comment.

### Steps to reproduce

1. create public or workspace memo.
2. put comment by one user, 
3. put comment by another user.
4. on memos list shown comments  counter = 2
5. on detailed page - counter = 1 and only one own comment shown, comment by another user is not visible.

### The version of Memos you're using

v0.24.2

**Comment by johnnyjoygh** [comment]
Fixed with https://github.com/usememos/memos/commit/08f9b18ced6f252dff2e2ed64d85120050534d25

**Comment by szonov** [comment]
It is not completely fixed.
now happens situation - in web I see only OWN comments, in api I see ALL comments.
I suppose visibility of comments show be the same for web and api.
By me opinion comments for shared memos (PUBLIC or WORKSPACE)  should be visible for all users, which have permissions to see this memo, but not only for owner of comment. I see comments is something like discussion.
