### ISSUE TITLE
Mermaid diagram and Code coloring not working in new themes

### ISSUE THREAD

**Issue by nebula-it** [usememos/memos#4891]
### Describe the bug

With the new `v0.25.0` release the theme has been changed and there is an option to select a theme now. However none of those themes work as well as the old one. Two major issues are mermaid diagram not showing up the arrows properly and any code snippets not being colored. Here is the screenshot from `v0.25.0` :

<img width="813" height="680" alt="Image" src="https://github.com/user-attachments/assets/44a87a32-3fb3-49ef-8b5f-377e9b7d199e" />

and here is the same from `v0.24.0`:

<img width="856" height="698" alt="Image" src="https://github.com/user-attachments/assets/d6dec4b1-aa41-4b42-acd1-2ca6459fd892" />

### Steps to reproduce

Here is the sample text used for above screenshots if you want to try and reproduce. Remove the `\` at the end of ```, that was to escape github markdown

```
```mermaid
graph TD;
    Data-SP-->Bay4;
    Data-SP-->Bay5;
    Data-SP-->Bay14;
    Data-SP-->Bay15;
```\
```powershell
$jobs = 1..10
foreach($job in $jobs){
    $tempPath = "D:\job" + $job
    Start-Process chia.exe -ArgumentList "plots create -k 32 -b 4096 -u 128 -r 8 -t $tempPath  -d Z:\ -n 8"
    Start-Sleep -Seconds 2400
}
```\
```

### The version of Memos you're using

v0.25.0

### Screenshots or additional context

Any chance we can re-add the theme from v0.24.0? It also seems to be easier to read, since it has better contrast. (I'd probably make the fonts a bit more white so improve it even further)

**Comment by boojack** [comment]
fixed in https://github.com/usememos/memos/commit/d7ced7b73867867b999f46756b62f00cd45c7f2d

**Comment by nebula-it** [comment]
Hey @boojack 
Seems like this issue is back on `0.25.2`. The blocks are rendering in white again (for the default dark theme).

Also, can we please revert the default Dark Theme to [this](https://github.com/usememos/memos/blob/36b5627ec3806749ece656d8964cde13b7e17a70/web/src/themes/default.css#L52). It was changed to [this](https://github.com/usememos/memos/blob/36b5627ec3806749ece656d8964cde13b7e17a70/web/src/themes/paper.css#L52) in [this](https://github.com/usememos/memos/pull/4824/files#diff-ab4fa96aefbcd454b03dc8301dd2af56f746fc6a41f269fe4cb8031ffd5f4b43) commit. But the old dark theme is much more easier to read.
