### ISSUE TITLE
Some issues on mobile v0.25.0.

### ISSUE THREAD

**Issue by f4rux** [usememos/memos#4896]
### Describe the bug

1. after opening the top page, pressing the tag button in the new post field does not load the existing tags.

If you open the hamburger menu and try again, it will load. 

2. cannot change settings on the settings page and cannot open any settings page except account settings.

### Steps to reproduce

These problems only occur when v0.25.0 is opened in a mobile browser.
When opened on a PC, there is no problem. Also, previous versions did not have these problems.

### The version of Memos you're using

v0.25.0

**Comment by ginjugg** [comment]
This will probably help you:
https://github.com/mudkipme/MoeMemosAndroid/issues/264

**Comment by johnnyjoygh** [comment]
@f4rux These should be fixed in the latest v0.25.0, please try to pull the image again.

**Comment by f4rux** [comment]
@johnnyjoygh 
It is still broken.

> These should be fixed in the latest v0.25.0, 

What does this mean?
I have never encountered this bug before v0.25.0

**Comment by kangminsukdotcom** [comment]
In addition to this problem, after upgrading to 0.25, I can't write comments on mobile devices.

**Comment by christippett** [comment]
Experiencing the same issue. I'm on mobile so haven't had a chance to inspect using dev tools, but it seems like there's a container blocking UI actions.

**Comment by christippett** [comment]
The culprit seems to be that `style="pointer-events: none;"` gets applied to `<body>` when opening the nav drawer and then doesn't get removed once you've navigated to another page. Manually disabling the style fixes the issue and you can interact with the page as normal.

**Comment by christippett** [comment]
Given @hchengting's merged PR has addressed and fixed the issue, wouldn't it be more appropriate to mark this as resolved?

**Comment by giacomocerquone** [comment]
@christippett not only that, but I still see this issue in the latest published docker image.

@boojack do you have a ETA for the next release that will include this? Thanks 🙏
