### ISSUE TITLE
Fail to create Memo in v0.25.0 / postgres

### ISSUE THREAD

**Issue by vladimirdulov** [usememos/memos#4903]
### Describe the bug

Hello, 

Memos v0.25.0
postgres v16.8

When saving a memo, an error appers:

```
ERROR server error method=/memos.api.v1.MemoService/ListMemos error="failed to convert memo: failed to list memo relations: pq: got 4 parameters but the statement requires 3"
```

### Steps to reproduce

1. login
2. click Save ( Memo)
3. Nothing happens, UI and app log shows the error:

```
ERROR server error method=/memos.api.v1.MemoService/ListMemos error="failed to convert memo: failed to list memo relations: pq: got 4 parameters but the statement requires 3"
```

### The version of Memos you're using

0.24.4, 0.25.0

**Comment by johnnyjoygh** [comment]
@vladimirdulov It should be fixed in the latest v0.25.0, please try to pull the image again.

**Comment by vladimirdulov** [comment]
I'm sorry but the issue still persists in v0.25.0.

<img width="994" height="150" alt="Image" src="https://github.com/user-attachments/assets/b174ad1e-6c18-4c66-bf5b-45b61a4ea597" />

**Comment by nerdteacher** [comment]
I'm having the same problem, and I only updated a couple days ago. (And making posts was working as of July 8 on the previous version, when I made my last note.) And a fresh install as a test elsewhere currently results in the same.

On top of that, all of the post content that I already wrote isn't showing, and I'm wondering if that's related, too. (Tags show with number of posts using them, attached images show, the calendar shows the days the posts were made and how many, posts with links show how many exist... just receiving "no data found" for the post content and nothing else. (Let me know if I should start another thread instead of piggy-backing here, since I'm pondering if the two are related.)

**Comment by brandnewmath** [comment]
I'm experiencing this same error (PostgreSQL 17.4), and I just installed today.

I notice you marked this `need more context`--what could we provide that would be helpful?

Edit--After a little more digging, I found that notes seem to be _stored_ in the database just fine, it's _retrieving_ them that's causing the error. If you `SELECT * FROM memos;` in your database, you can see a row containing each note you tried to save. I hope this is helpful!

Edit 2--I went to the trouble of building from HEAD, using my existing database and config etc., and was able to save and see a note normally there, so this *may* have been fixed in the dev version already--someone should check my work, though, I'm not really a developer!

**Comment by richie-tt** [comment]
I have the same error: 

```sh
│ 2025/08/18 09:28:28 INFO OK method=/memos.api.v1.InboxService/ListInboxes                                                                                                                                      │
│ 2025/08/18 09:28:28 ERROR server error method=/memos.api.v1.MemoService/ListMemos error="failed to convert memo: failed to list memo relations: pq: got 4 parameters but the statement requires 3"             │
│ 2025/08/18 09:28:28 INFO OK method=/memos.api.v1.UserService/GetUserStats                                                                                                                                      │
│ 2025/08/18 09:28:38 ERROR server error method=/memos.api.v1.MemoService/ListMemos error="failed to convert memo: failed to list memo relations: pq: got 4 parameters but the statement requires 3"             │
│ 2025/08/18 09:28:46 ERROR server error method=/memos.api.v1.MemoService/ListMemos error="rpc error: code = Internal desc = failed to list memos: pq: operator does not exist: integer = text"                  │
│ 2025/08/18 09:28:48 INFO OK method=/memos.api.v1.ShortcutService/ListShortcuts                                                                                                                                 │
│ 2025/08/18 09:28:48 ERROR server error method=/memos.api.v1.MemoService/ListMemos error="failed to convert memo: failed to list memo relations: pq: got 4 parameters but the statement requires 3"             │
│ 2025/08/18 09:28:48 INFO OK method=/memos.api.v1.UserService/GetUserStats                                                                                                                                      │
│ 2025/08/18 09:28:56 INFO OK method=/memos.api.v1.AttachmentService/ListAttachments                                                                                                                             │
│ 2025/08/18 09:28:56 ERROR server error method=/memos.api.v1.MemoService/GetMemo error="failed to convert memo: failed to list memo relations: pq: got 4 parameters but the statement requires 3"               │
│ 2025/08/18 09:28:56 ERROR server error method=/memos.api.v1.MemoService/GetMemo error="failed to convert memo: failed to list memo relations: pq: got 4 parameters but the statement requires 3"               │
│ 2025/08/18 09:28:56 ERROR server error method=/memos.api.v1.MemoService/GetMemo error="failed to convert memo: failed to list memo relations: pq: got 4 parameters but the statement requires 3"               │
│ 2025/08/18 09:28:56 ERROR server error method=/memos.api.v1.MemoService/GetMemo error="failed to convert memo: failed to list memo relations: pq: got 4 parameters but the statement requires 3"               │
│ 2025/08/18 09:28:58 ERROR server error method=/memos.api.v1.MemoService/ListMemos error="rpc error: code = Internal desc = failed to list memos: pq: operator does not exist: integer = text"                  │
│ 2025/08/18 09:28:59 INFO OK method=/memos.api.v1.ShortcutService/ListShortcuts                                                                                                                                 │
│ 2025/08/18 09:28:59 ERROR server error method=/memos.api.v1.MemoService/ListMemos error="failed to convert memo: failed to list memo relations: pq: got 4 parameters but the statement requires 3"             │
│ 2025/08/18 09:28:59 INFO OK method=/memos.api.v1.UserService/GetUserStats                                                                                                                                      │
│ 2025/08/18 09:29:08 ERROR server error method=/memos.api.v1.MemoService/ListMemos error="failed to convert memo: failed to list memo relations: pq: got 4 parameters but the statement requires 3"
```

How I can solve it ?

**Comment by halictuz** [comment]
same here, I even tried the 11notes version (11notes/docker-memos)  but the same issue, doesnt work. too bad, I really wanted to try and use memos. I hope this gonna be fixed. Thanks for the work so far. 
When adding text, it doesnt work, but when adding images, they show up on attachments page just fine, but not in the post/memos.

`failed to convert memo: failed to list memo relations: pq: got 4 parameters but the statement requires 3`

**Comment by richie-tt** [comment]
I switched to version `0.24.4`, and everything started working correctly. I use PostgreSQL as a database backend for Memos.

**Comment by Novapixel1010** [comment]
When you upgrade your container did you just change the tag or make a pull for an update? I did a backup/restore and everything seems to work. I wrote a guide about how to backup and restore [here](https://guide.hypernovat.com/s/0d3bca9e-c7b4-4a87-91b0-59dc78345c6d/doc/memos-N9rII1Yp7I) Maybe changing just the tag is causing weird issues.

**Comment by DenzoNL** [comment]
I also get this same error, using the version in nixpkgs unstable (v0.25.0), but still running postgres 14.
I only installed it today so the database migration is fresh and empty.

**Comment by richie-tt** [comment]
> When you upgrade your container did you just change the tag or make a pull for an update? I did a backup/restore and everything seems to work. I wrote a guide about how to backup and restore [here](https://guide.hypernovat.com/s/0d3bca9e-c7b4-4a87-91b0-59dc78345c6d/doc/memos-N9rII1Yp7I) Maybe changing just the tag is causing weird issues.

I just updated the memos version from `0.24.4` to `0.25.0` and the problem showed up, I tried your approach @Novapixel1010, but I ended up with another strange error. I had to make a mistake, will try again with your approach.

btw, @Novapixel1010 you have many interesting guides :), what software do you use to create this brilliant wiki ?

**Comment by oluceps** [comment]
> I just updated the memos version from 0.24.4 to 0.25.0 and the problem showed up

same issue

**Comment by Novapixel1010** [comment]
@richie-tt  I use a software called outline I might make a guide on it. When I am done finishing some other guides

**Comment by DenzoNL** [comment]
I've debugged this and it seems like the problem is already fixed in versions newer than v0.25.0, by this commit: https://github.com/usememos/memos/commit/40130350c57898c60274153376bb6d858844ce17, which is the commit right after the v0.25.0 release tag.

It seems like all that's needed is to push a tag for v0.25.1 (it seems like this release was created but never pushed as a tag?) or just create a new release.

I've tested both the commit above and the latest main on my local machine and it works just fine with Postgres :)

**Comment by dminca** [comment]
the issue persists in `v0.25.3` with PostgreSQL `17.11` as backend.

```
Aug 25 13:41:33 notes-nixos-01 memos[48070]: 2026/08/25 13:41:33 ERROR server error method=/memos.api.v1.MemoService/ListMemos error="rpc error: code = Internal desc = failed to list memos: pq: operator does not exist: jsonb ~~ unknown" stacktrace="rpc error: code = Internal desc = failed to list memos: pq: operator does not exist: jsonb ~~ unknown"
```

You can repro this in the following way
1. head over to Settings > Memo
2. increase **Content length limit (Byte)** to `99999999`
3. publish some big markdown in your memos
4. repeat 1, 2 but this time reset to its default `8192`
5. search for a tag

Expected

- only the matches to show in results

Actual

- all your memos listed regardless of your search filters
