### ISSUE TITLE
Appears light background after refreshing, even set dark theme

### ISSUE THREAD

**Issue by winsphinx** [usememos/memos#5119]
### Describe the bug

After setting dark theme, it shows light page when refreshing the page, after the page loaded, it returns to dark.
Thus hurts eyes.

### Steps to reproduce

1. set dark theme
2. refresh page
3. it shows light

### The version of Memos you're using

v0.25.1

**Comment by johnnyjoygh** [comment]
Fixed in https://github.com/usememos/memos/commit/f6e025d5833eb1f68761f34910ca2172d6cfe469

**Comment by potados99** [comment]
White background still appears. 

v0.25.3
iOS 26.1 Safari
System is set to dark mode.

https://github.com/user-attachments/assets/1b6371b4-65f2-48be-b326-4de6f80c0d6c
