### ISSUE TITLE
Restarting the container gets users kicked out of their session

### ISSUE THREAD

**Issue by sebw** [usememos/memos#775]
### Describe the bug

A simple docker restart and cookies are no longer valid. All users are kicked out (browser, mobile app).

Resulting in 401 Missing user in session in container logs.

### Steps to reproduce

- docker start memos
- log in browser and mobile app
- docker restart memos
- docker logs -f memos
- refresh browser or mobile app

**Comment by crishnakh** [comment]
Yesterday i give a try to memos, all was good. Today I upgraded to latest version and I'm having this issue. Recreate or reinstall with docker and still this error.

**Comment by m4mazzotti** [comment]
Same issue here. I did try to reinstall and with iOS device and I got 401 Missing user in session.

**Comment by daviesgeek** [comment]
Also have this issue, tried removing the container and all the data to re-install. Cleared the application cookies in the browser, still had the same issue signing up and signing in.

**Comment by enriquetoledano** [comment]
Same problem here, upgrading from 0.8.3 to 0.9.0

**Comment by crishnakh** [comment]
Downgrade fix the error, I will stay on 0.8.3 until new version or fix the problem.

**Comment by daviesgeek** [comment]
Seems like it's an http vs https error. Try running it on https and it'll fix it

**Comment by m-gschwandtner** [comment]
> Seems like it's an http vs https error. Try running it on https and it'll fix it

0.8.3 and 0.9.0 both seem to invalidate the session on http as far as i can tell

**Comment by m4mazzotti** [comment]
If anyone is wondering how to pull an older version, replace
`neosmemo/memos:latest`
with
`neosmemo/memos:0.8.3`

**Comment by raisinbear** [comment]
@daviesgeek sorry for the probably dumb question, but how is
> Seems like it's an http vs https error. Try running it on https and it'll fix it

to be done? In the quite brief deployment section I cannot find a flag telling the application to serve via https. Or does this apply to a reverse proxy config?
Thanks :)

**Comment by sebw** [comment]
My instance runs on a valid https cert behind a cloudflare tunnel. Can you elaborate @m-gschwandtner ?

**Comment by daviesgeek** [comment]
> @daviesgeek sorry for the probably dumb question, but how is
> 
> > Seems like it's an http vs https error. Try running it on https and it'll fix it
> 
> 
> 
> to be done? In the quite brief deployment section I cannot find a flag telling the application to serve via https. Or does this apply to a reverse proxy config? If so, would you mind sharing your config?
> 
> Thanks :)

Ya I have it behind a reverse proxy and it started worked. It sounds like the issue has been fixed though.

**Comment by sebw** [comment]
Upgrade to latest and problem persists for me (behind Cloudflare tunnel).

**Comment by raisinbear** [comment]
Same here. And I’m using nginx as a reverse proxy with valid ssl certificate. Getting kicked out of my sessions on each restart..

**Comment by crishnakh** [comment]
Any news about this?
